name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: setup
        uses: luxass/shared-workflows/actions/setup@4e838e75ef8e2f2f71872efb5a84715866a14254 # actions/setup/v0.1.1
        with:
          node-version: lts/*
          persist-credentials: false

      - name: fmt
        run: pnpm fmt:check

      - name: validate renovate config
        run: pnpm validate:renovate
